const tr={home:"Ana Sayfa",ph:"Felsefe",articles:"Yazılar",software:"Yazılım",gallery:"Fotoğraf Arşivi",projects:"Projeler",contact:"İletişim",eyebrow:"KİŞİSEL ALAN / FOTOĞRAF ARŞİVİ",hero:"Doğa,<br><em>hafıza,</em><br>özgürlük.",lead:"Felsefe, bilim, tarih, yazılım ve doğa arasında dolaşan kişisel bir alan.",photos:"Fotoğraflara geç →"};
const en={home:"Home",ph:"Philosophy",articles:"Articles",software:"Software",gallery:"Photo Archive",projects:"Projects",contact:"Contact",eyebrow:"PERSONAL SPACE / PHOTO ARCHIVE",hero:"Nature,<br><em>memory,</em><br>freedom.",lead:"A personal space between philosophy, science, history, software and nature.",photos:"Go to photos →"};
const fr={home:"Accueil",ph:"Philosophie",articles:"Articles",software:"Logiciels",gallery:"Archives photo",projects:"Projets",contact:"Contact",eyebrow:"ESPACE PERSONNEL / ARCHIVES PHOTO",hero:"Nature,<br><em>mémoire,</em><br>liberté.",lead:"Un espace personnel entre philosophie, science, histoire, logiciels et nature.",photos:"Voir les photos →"};
const de={home:"Startseite",ph:"Philosophie",articles:"Texte",software:"Software",gallery:"Fotoarchiv",projects:"Projekte",contact:"Kontakt",eyebrow:"PERSÖNLICHER RAUM / FOTOARCHIV",hero:"Natur,<br><em>Erinnerung,</em><br>Freiheit.",lead:"Ein persönlicher Raum zwischen Philosophie, Wissenschaft, Geschichte, Software und Natur.",photos:"Zu den Fotos →"};
const dict={tr,en,fr,de};
const articles={
tr:{spinoza:`<h1>Spinoza: Özgürlük ve Zorunluluk</h1><p>Özgürlük çoğu zaman istediğini yapabilmek olarak düşünülür. Spinoza için mesele bundan çok daha karmaşıktır. İnsan doğanın dışında duran bağımsız bir varlık değildir; doğanın zorunluluğunun bir parçasıdır.</p><h2>Tanrı ya da Doğa</h2><p>Spinoza'nın <i>Ethica</i>'sının merkezinde <b>Deus sive Natura — Tanrı ya da Doğa</b> düşüncesi bulunur. Doğanın dışında ona müdahale eden aşkın bir güç yoktur. İnsan da bu nedensellik düzeninin dışına çıkamaz.</p><h2>Özgür olduğumuzu neden düşünüyoruz?</h2><p>İnsan kendi arzularının farkındadır fakat bu arzuların nedenlerini çoğu zaman bilmez. Bu yüzden kendisini özgür zanneder. Gerçek özgürlük, davranışlarımızı meydana getiren nedenleri anlamaya başlamaktır.</p><h2>Özgürlük nedir?</h2><p>Özgür olmak zorunluluktan kaçmak değil, zorunluluğu kavramaktır. Korku, öfke ve tutkularımızın nasıl oluştuğunu anladıkça daha etkin hale geliriz.</p><h2>Conatus</h2><p>Her varlık kendi varlığını sürdürmeye ve geliştirmeye çalışır. Spinoza buna <b>conatus</b> der. İnsan için bu yalnızca hayatta kalmak değil, bilmek, sevmek, üretmek ve varoluş gücünü artırmaktır.</p><h2>Sonuç</h2><p>İnsan zorunluluktan kurtularak değil, zorunluluğu anlayarak özgürleşir. Özgürlük doğanın karşısında durmak değil, doğanın bir parçası olduğumuzu kavrayarak onun içinde daha etkin bir yaşam kurabilmektir.</p><div class="signature">— Troçki</div>`,
anarchism:`<h1>Anarşizm: Özgürlüğün ve Dayanışmanın Felsefesi</h1><p>Anarşizm çoğu zaman düzensizlik veya kaos fikriyle özdeşleştirilir. Oysa merkezindeki soru, <b>insanın neden başkasının iradesine tabi olmak zorunda olduğu</b> sorusudur.</p><h2>Özgürlük ve otorite</h2><p>Anarşizm, bazı insanların sürekli karar verme gücünü elinde tutmasına ve diğerlerinin bu kararlara uymaya zorlanmasına itiraz eder.</p><p><b>Bir insan neden başka bir insan üzerinde yönetme hakkına sahip olmalıdır?</b></p><h2>Devletsiz toplum mümkün müdür?</h2><p>Öz-yönetim, gönüllü birliktelik, karşılıklı yardım ve federatif örgütlenmeler aracılığıyla toplumun kendisini yönetebileceği savunulur.</p><h2>Dayanışma</h2><p>Dayanışma yukarıdan verilen bir yardım değil, insanların yatay ilişkiler içinde ortak yaşam koşullarını iyileştirmesidir.</p><h2>Sonuç</h2><p>Anarşizm mevcut düzenin kaçınılmaz olmadığını hatırlatır. Daha yatay, özgür ve dayanışmacı ilişkiler mümkündür.</p><div class="signature">— Troçki</div>`},
en:{spinoza:`<h1>Spinoza: Freedom and Necessity</h1><p>Freedom is often understood as doing what one wants. For Spinoza, the matter is deeper: human beings are part of nature and its necessity.</p><h2>God or Nature</h2><p>At the center of the <i>Ethics</i> stands <b>Deus sive Natura — God or Nature</b>. Nothing stands outside nature's causal order.</p><h2>Why do we think we are free?</h2><p>We know our desires but often do not know their causes. Understanding those causes is the beginning of freedom.</p><h2>Freedom</h2><p>Freedom is not escape from necessity; it is understanding necessity.</p><h2>Conclusion</h2><p>We become freer not by escaping necessity, but by understanding it and becoming more active within nature.</p><div class="signature">— Troçki</div>`,anarchism:`<h1>Anarchism: The Philosophy of Freedom and Solidarity</h1><p>Anarchism is often reduced to chaos. Its central question is why one person should be subjected to another person's will.</p><h2>Freedom and authority</h2><p>Anarchist thought questions permanent concentrations of power and compulsory hierarchy.</p><h2>Solidarity</h2><p>Solidarity is horizontal cooperation rather than charity from above.</p><h2>Conclusion</h2><p>Anarchism reminds us that the existing order is not inevitable. Freer and more horizontal relationships are possible.</p><div class="signature">— Troçki</div>`},
fr:{spinoza:`<h1>Spinoza : Liberté et nécessité</h1><p>La liberté est souvent comprise comme la possibilité de faire ce que l'on veut. Pour Spinoza, l'être humain fait partie de la nature et de sa nécessité.</p><h2>Dieu ou Nature</h2><p>Au centre de l'<i>Éthique</i> se trouve <b>Deus sive Natura — Dieu ou Nature</b>. Rien n'est extérieur à l'ordre causal de la nature.</p><h2>Pourquoi nous croyons-nous libres ?</h2><p>Nous connaissons nos désirs mais ignorons souvent leurs causes. Les comprendre est le début de la liberté.</p><h2>Conclusion</h2><p>Nous devenons libres non en échappant à la nécessité, mais en la comprenant.</p><div class="signature">— Troçki</div>`,anarchism:`<h1>Anarchisme : la philosophie de la liberté et de la solidarité</h1><p>L'anarchisme est souvent réduit au chaos. Sa question centrale est pourquoi une personne devrait être soumise à la volonté d'une autre.</p><h2>Liberté et autorité</h2><p>La pensée anarchiste critique la concentration du pouvoir et les hiérarchies imposées.</p><h2>Solidarité</h2><p>La solidarité est horizontale et repose sur la coopération.</p><h2>Conclusion</h2><p>L'ordre existant n'est pas inévitable. Une société plus libre et horizontale est pensable.</p><div class="signature">— Troçki</div>`},
de:{spinoza:`<h1>Spinoza: Freiheit und Notwendigkeit</h1><p>Freiheit wird oft als die Möglichkeit verstanden, zu tun, was man will. Für Spinoza ist der Mensch Teil der Natur und ihrer Notwendigkeit.</p><h2>Gott oder Natur</h2><p>Im Zentrum der <i>Ethik</i> steht <b>Deus sive Natura — Gott oder Natur</b>. Nichts steht außerhalb der kausalen Ordnung der Natur.</p><h2>Warum halten wir uns für frei?</h2><p>Wir kennen unsere Wünsche, aber oft nicht ihre Ursachen. Diese zu verstehen ist der Beginn der Freiheit.</p><h2>Fazit</h2><p>Wir werden nicht frei, indem wir der Notwendigkeit entkommen, sondern indem wir sie verstehen.</p><div class="signature">— Troçki</div>`,anarchism:`<h1>Anarchismus: Die Philosophie von Freiheit und Solidarität</h1><p>Anarchismus wird oft mit Chaos gleichgesetzt. Im Zentrum steht die Frage, warum ein Mensch dem Willen eines anderen unterworfen sein sollte.</p><h2>Freiheit und Autorität</h2><p>Anarchistisches Denken kritisiert die Konzentration von Macht und erzwungene Hierarchien.</p><h2>Solidarität</h2><p>Solidarität ist horizontale Zusammenarbeit statt Hilfe von oben.</p><h2>Fazit</h2><p>Die bestehende Ordnung ist nicht unvermeidlich. Eine freiere und horizontalere Gesellschaft ist denkbar.</p><div class="signature">— Troçki</div>`}};
let lang=localStorage.getItem("trockiLang")||"tr";
function setLang(l){lang=l;localStorage.setItem("trockiLang",l);document.documentElement.lang=l;document.querySelectorAll("[data-i]").forEach(e=>{if(dict[l][e.dataset.i])e.innerHTML=dict[l][e.dataset.i]});document.querySelectorAll("[data-lang]").forEach(e=>e.classList.toggle("active",e.dataset.lang===l))}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(lang);

const nav=document.getElementById("nav"),menu=document.getElementById("menuBtn");menu.onclick=()=>nav.classList.toggle("open");nav.querySelectorAll("a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
const modal=document.getElementById("modal"),modalArticle=document.getElementById("modalArticle");document.querySelectorAll("[data-article]").forEach(b=>b.onclick=()=>{modalArticle.innerHTML=articles[lang][b.dataset.article];modal.classList.add("open")});document.getElementById("closeModal").onclick=()=>modal.classList.remove("open");

const input=document.getElementById("photoInput"),grid=document.getElementById("galleryGrid"),empty=document.getElementById("empty"),key="trockiGalleryV4";let photos=JSON.parse(localStorage.getItem(key)||"[]");
function render(){grid.innerHTML="";empty.style.display=photos.length?"none":"block";photos.forEach((src,i)=>{const box=document.createElement("div");box.className="photo";const img=document.createElement("img");img.src=src;img.onclick=()=>{modalArticle.innerHTML='<img style="max-width:100%" src="'+src+'">';modal.classList.add("open")};const d=document.createElement("button");d.className="delete";d.textContent="×";d.onclick=e=>{e.stopPropagation();photos.splice(i,1);localStorage.setItem(key,JSON.stringify(photos));render()};box.append(img,d);grid.append(box)})}
input.onchange=()=>[...input.files].forEach(f=>{if(!f.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>{photos.unshift(r.result);localStorage.setItem(key,JSON.stringify(photos));render()};r.readAsDataURL(f)});document.getElementById("clearBtn").onclick=()=>{if(confirm("Fotoğraflar silinsin mi?")){photos=[];localStorage.setItem(key,"[]");render()}};render();
